### ISSUE TITLE
README inference does not work?

### ISSUE THREAD

**Issue by rlenain** [gallilmaimon/DISSC#1]
Hi there,

Firstly, thanks for your work and for open sourcing this code. It's truly appreciated!
I am trying to recreate the instructions in the README to infer with an "in the wild speaker". Specifically I am running: 

```bash
python3 data/preprocess.py --srcdir data/unseen/wav_orig --outdir data/unseen/wav --pad --postfix .wav

python3 data/encode.py --base_dir data/unseen/wav --out_file data/unseen/hubert100/encoded.txt --device cuda:1

python3 infer.py --input_path data/unseen/hubert100/encoded.txt --out_path data/unseen/pred_hubert/ --pred_len \
--pred_pitch --len_model checkpoints/syn_vctk/len/ --f0_model checkpoints/syn_vctk/pitch/ \ 
--f0_path data/Syn_VCTK/hubert100/f0_stats.pkl --vc --target_speakers p231 p239 p245 p270 --wild_sample \ 
--id_to_spkr data/Syn_VCTK/hubert100/id_to_spkr.pkl

python3 sr/inference.py --input_code_file data/unseen/hubert100/p231_encoded.txt --data_path data/unseen/wav \ 
--output_dir dissc_p231 --checkpoint_file sr/checkpoints/vctk_hubert --unseen_speaker \ 
--id_to_spkr data/Syn_VCTK/hubert100/id_to_spkr.pkl
```

but the last command fails: 
```bash
Traceback (most recent call last):
  File "sr/inference.py", line 363, in <module>
    main()
  File "sr/inference.py", line 320, in main
    file_list = parse_manifest(a.input_code_file, base_path)
  File "/home/raph/repos/DISSC/sr/dataset.py", line 111, in parse_manifest
    with open(manifest) as info:
FileNotFoundError: [Errno 2] No such file or directory: 'data/unseen/hubert100/p231_encoded.txt'
```

I figured perhaps you had a typo, where `--input_code_file` is actually meant to be `data/unseen/pred_hubert/p231_encoded.txt`, so when I switch that argument, the code runs successfully, but the `dissc_p231` folder only contains `s1_1_gt.wav` and `s1_1_gt.wav`, which are simply the ground truths. Inspecting the code a little bit, all the if statements are returning `False`, so the only thing the code does is dump the ground truths to the folder.

Any tips on what needs to change?

Thanks a lot!

**Comment by gallilmaimon** [comment]
Hey,

thanks for noticing. It looks like there might be a small typo in the last command of the "in the wild speakers". You are correct that `--input_code_file data/unseen/pred_hubert/p231_encoded.txt` should be used so that we use the predicted durations and pitch!

However, it seems that I also missed the flag `--vc` in the inference script which tells the speech resynthesis model to perform VC (which is the only possible output for unknown speakers, as resynthesis for unknown speakers is not supported). Let me know if that solves the issue as expected:) Anyway, I will inspect that bit further and update the readme accordingly as soon as I get a chance.

**Comment by rlenain** [comment]
Yes that worked! Thanks a lot
